name: Swag Labs Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # schedule:
  #   # Run daily at midnight
  #   - cron: '0 0 * * *'
  # workflow_dispatch:
  #   # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run tests
      # -Dheadless=true: Ensures tests run in headless mode.
      # -Dci=true: Explicitly informs WebDriverManager it's a CI environment.
      # -Dmaven.test.failure.ignore=false: CRITICAL - Overrides pom.xml setting to ensure test failures fail the build.
      # -Dtest=AllTests: Runs the specified test suite (assuming AllTests.java is your main test suite).
      run: mvn clean test -Dheadless=true -Dci=true -Dmaven.test.failure.ignore=false -Dtest=AllTests
    
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/
          test-screenshots/
    
    - name: Generate test report
      if: always()
      run: mvn surefire-report:report-only
    
    - name: Publish test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: target/site/
